import {
  balloon,
  balloonBunch,
  banner,
  bg,
  bunting,
  cake,
  candle,
  cloud,
  confetti,
  cupcake,
  diagonalStripes,
  dots,
  flower,
  frame,
  gift,
  leafSprig,
  nameLine,
  numeral,
  PALETTES,
  partyHat,
  photoFrame,
  rocket,
  scallop,
  sparkle,
  sparkles,
  star5,
  sun,
  title,
  titleLines,
  twoLines,
} from '../primitives';
import { H, W } from '../scene';
import { def, type DesignDef } from '../types';

const P = PALETTES;

export const birthday: DesignDef[] = [
  def({
    id: 'bday-balloon-bunch',
    title: 'Balloon bunch',
    occasions: ['birthday'],
    tags: ['cute', 'for her', 'for him'],
    supportsPhoto: false,
    tint: 'butter',
    palette: 'coral',
    scene: (i) => [
      ...bg(P.coral.bg),
      ...dots(P.coral.a, 6, 9, 2.2, 0.18),
      ...bunting(30, [P.coral.a, P.coral.b, P.coral.c, P.coral.d], 18, 8),
      ...balloonBunch(W / 2, 150, [P.coral.a, P.coral.c, P.coral.b, P.coral.d, '#FF8FA3'], 30),
      ...titleLines(twoLines(i.title), 300, 30, { size: 28, color: P.coral.ink }),
      ...nameLine(i.name, 352, P.coral.a),
    ],
  }),
  def({
    id: 'bday-big-number',
    title: 'Big number',
    occasions: ['birthday'],
    tags: ['milestone', 'minimal'],
    supportsPhoto: false,
    tint: 'butter',
    palette: 'butter',
    scene: (i) => [
      ...bg(P.butter.bg),
      ...diagonalStripes(P.butter.a, 7, 18, 0.14),
      ...numeral(i.age, 205, i.age != null && i.age >= 100 ? 130 : 168, P.butter.b, '40'),
      ...banner(W / 2, 262, 176, 34, P.butter.c, i.title, '#FFFFFF', 15),
      ...sparkles(3, 8, P.butter.a, { x: 20, y: 40, w: W - 40, h: 130 }, 6),
      ...nameLine(i.name, 330, P.butter.ink, 24),
    ],
  }),
  def({
    id: 'bday-cake-stack',
    title: 'Cake stack',
    occasions: ['birthday'],
    tags: ['cute', 'for kids', 'for her'],
    supportsPhoto: false,
    tint: 'blush',
    palette: 'blush',
    scene: (i) => [
      ...bg(P.blush.bg),
      ...confetti(11, 26, [P.blush.a, P.blush.d, P.blush.c, '#FFFFFF'], {
        x: 10,
        y: 10,
        w: W - 20,
        h: 120,
      }),
      ...titleLines(twoLines(i.title), 62, 30, { size: 26, color: P.blush.c }),
      ...cake(W / 2, 300, 150, [P.blush.b, P.blush.a, '#FFFFFF'], 5, P.blush.c),
      ...nameLine(i.name, 348, P.blush.a),
    ],
  }),
  def({
    id: 'bday-confetti-pop',
    title: 'Confetti pop',
    occasions: ['birthday'],
    tags: ['funny', 'for him', 'for her'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'paper',
    scene: (i) => [
      ...bg(P.paper.bg),
      ...confetti(7, 64, [P.paper.a, P.paper.b, P.paper.c, P.paper.d, '#FF8FA3']),
      {
        tag: 'rect',
        attrs: {
          x: 32,
          y: 128,
          width: W - 64,
          height: 118,
          rx: 14,
          fill: '#FFFFFF',
          opacity: 0.92,
        },
      },
      ...title('happy', 172, { font: 'hand', size: 44, weight: 700, color: P.paper.ink }),
      ...title('birthday!', 224, { font: 'hand', size: 50, weight: 700, color: P.paper.a }),
      ...nameLine(i.name, 320, P.paper.c, 24),
    ],
  }),
  def({
    id: 'bday-party-hats',
    title: 'Party hats',
    occasions: ['birthday'],
    tags: ['cute', 'for kids', 'funny'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'sky',
    scene: (i) => [
      ...bg(P.sky.bg),
      ...bunting(28, [P.sky.a, P.sky.c, P.sky.d, '#FFFFFF'], 16, 8),
      ...partyHat(70, 250, 96, P.sky.a, '#FFFFFF'),
      ...partyHat(132, 262, 122, P.sky.c, P.sky.d),
      ...partyHat(196, 250, 96, P.sky.d, P.sky.a),
      ...confetti(5, 18, [P.sky.a, P.sky.c, P.sky.d], { x: 20, y: 90, w: W - 40, h: 120 }),
      ...titleLines(twoLines(i.title), 300, 30, { size: 28, color: P.sky.ink }),
      ...nameLine(i.name, 352, P.sky.a),
    ],
  }),
  def({
    id: 'bday-cupcakes',
    title: 'Cupcake row',
    occasions: ['birthday'],
    tags: ['cute', 'for her', 'for kids'],
    supportsPhoto: false,
    tint: 'mint',
    palette: 'mint',
    scene: (i) => [
      ...bg(P.mint.bg),
      ...scallop('#FFFFFF', 70, 16, true),
      ...titleLines(twoLines(i.title), 34, 28, { size: 24, color: P.mint.a }),
      ...cupcake(62, 250, 60, P.mint.a, P.mint.d, P.mint.c),
      ...cupcake(132, 262, 74, P.mint.c, '#FFFFFF', P.mint.d),
      ...cupcake(202, 250, 60, P.mint.d, P.mint.b, P.mint.c),
      ...dots(P.mint.a, 5, 4, 2.5, 0.18, 280),
      ...nameLine(i.name, 336, P.mint.ink, 24),
    ],
  }),
  def({
    id: 'bday-photo-frame',
    title: 'Photo frame birthday',
    occasions: ['birthday'],
    tags: ['photo upload', 'for her', 'for him'],
    supportsPhoto: true,
    tint: 'butter',
    palette: 'paper',
    scene: (i) => [
      ...bg(P.paper.bg),
      ...bunting(24, [P.paper.a, P.paper.b, P.paper.c, P.paper.d], 14, 7),
      ...photoFrame(48, 78, W - 96, 176, '#FFFFFF'),
      ...confetti(9, 14, [P.paper.a, P.paper.b, P.paper.c], { x: 20, y: 60, w: W - 40, h: 220 }),
      ...titleLines(twoLines(i.title), 300, 28, { size: 26, color: P.paper.ink }),
      ...nameLine(i.name, 350, P.paper.a),
    ],
  }),
  def({
    id: 'bday-botanical',
    title: 'Botanical birthday',
    occasions: ['birthday'],
    tags: ['floral', 'for her'],
    supportsPhoto: false,
    tint: 'blush',
    palette: 'sand',
    scene: (i) => [
      ...bg(P.sand.bg),
      ...leafSprig(30, 130, 110, 35, P.sand.c, 6),
      ...leafSprig(W - 30, 130, 110, -35, P.sand.c, 6),
      ...leafSprig(40, 360, 100, 150, P.sand.c, 5),
      ...leafSprig(W - 40, 360, 100, -150, P.sand.c, 5),
      ...flower(48, 62, 22, 6, P.sand.a, P.sand.b),
      ...flower(W - 48, 62, 18, 6, P.sand.b, P.sand.a),
      ...flower(56, 322, 18, 5, P.sand.b, P.sand.a),
      ...flower(W - 56, 322, 22, 6, P.sand.a, P.sand.b),
      ...titleLines(twoLines(i.title), 172, 34, { size: 30, color: P.sand.ink }),
      ...nameLine(i.name, 232, P.sand.a, 26),
    ],
  }),
  def({
    id: 'bday-minimal-script',
    title: 'Simply script',
    occasions: ['birthday'],
    tags: ['minimal', 'for him', 'for her'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'paper',
    scene: (i) => [
      ...bg(P.paper.bg),
      ...frame(P.paper.ink, 14, 4, 1.5),
      ...title('happy', 160, { font: 'hand', size: 46, weight: 500, color: P.paper.ink }),
      ...title('birthday', 216, { font: 'hand', size: 56, weight: 700, color: P.paper.ink }),
      ...sparkle(56, 120, 8, P.paper.b),
      ...sparkle(212, 244, 7, P.paper.b),
      {
        tag: 'line',
        attrs: { x1: 100, y1: 250, x2: 164, y2: 250, stroke: P.paper.a, strokeWidth: 2 },
      },
      ...nameLine(i.name, 300, P.paper.a, 24),
    ],
  }),
  def({
    id: 'bday-gift-stack',
    title: 'Gift stack',
    occasions: ['birthday'],
    tags: ['cute', 'for kids', 'for him'],
    supportsPhoto: false,
    tint: 'lilac',
    palette: 'lilac',
    scene: (i) => [
      ...bg(P.lilac.bg),
      ...confetti(13, 30, [P.lilac.a, P.lilac.c, P.lilac.d, '#FFFFFF'], {
        x: 10,
        y: 10,
        w: W - 20,
        h: 150,
      }),
      ...gift(56, 200, 150, 90, P.lilac.a, P.lilac.c),
      ...gift(84, 130, 96, 72, P.lilac.d, '#FFFFFF'),
      ...gift(104, 78, 56, 52, P.lilac.c, P.lilac.a),
      ...titleLines(twoLines(i.title), 316, 28, { size: 26, color: P.lilac.ink }),
      ...nameLine(i.name, 362, P.lilac.a, 22),
    ],
  }),
  def({
    id: 'bday-rainbow',
    title: 'Rainbow day',
    occasions: ['birthday'],
    tags: ['for kids', 'cute'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'sky',
    scene: (i) => [
      ...bg(P.sky.bg),
      ...[P.sky.c, P.sky.d, '#7AD3B0', P.sky.a, P.sky.b].map((c, k) => ({
        tag: 'path' as const,
        attrs: {
          d: `M${20 + k * 14} 230 A${112 - k * 14} ${112 - k * 14} 0 0 1 ${W - 20 - k * 14} 230`,
          stroke: c,
          strokeWidth: 14,
          fill: 'none',
          strokeLinecap: 'round',
        },
      })),
      ...cloud(48, 232, 70, '#FFFFFF'),
      ...cloud(W - 48, 232, 70, '#FFFFFF'),
      ...sun(W - 56, 64, 22, P.sky.d, 12),
      ...titleLines(twoLines(i.title), 296, 30, { size: 28, color: P.sky.ink }),
      ...nameLine(i.name, 348, P.sky.a),
    ],
  }),
  def({
    id: 'bday-rocket',
    title: 'Blast off',
    occasions: ['birthday'],
    tags: ['for kids', 'for him'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'night',
    scene: (i) => [
      ...bg(P.night.bg),
      ...sparkles(21, 26, P.night.a, { x: 10, y: 10, w: W - 20, h: 260 }, 4),
      ...star5(48, 70, 9, P.night.b),
      ...star5(216, 110, 7, P.night.b),
      ...rocket(W / 2, 236, 130, P.night.d, P.night.c, P.night.a),
      ...title('Blast off!', 300, { size: 32, color: P.night.a }),
      ...title(i.title, 328, { size: 15, weight: 600, color: P.night.b, letterSpacing: 1 }),
      ...nameLine(i.name, 356, P.night.c, 22),
    ],
  }),
  def({
    id: 'bday-milestone-stars',
    title: 'Milestone stars',
    occasions: ['birthday'],
    tags: ['milestone', 'for him', 'for her'],
    supportsPhoto: false,
    tint: 'lilac',
    palette: 'night',
    scene: (i) => [
      ...bg(P.night.bg),
      ...sparkles(31, 34, P.night.a, undefined, 4),
      ...star5(40, 56, 12, P.night.d),
      ...star5(222, 300, 10, P.night.c),
      ...numeral(i.age, 208, i.age != null && i.age >= 100 ? 120 : 150, P.night.a, '30'),
      ...title('years of brilliant', 252, {
        font: 'hand',
        size: 34,
        weight: 700,
        color: P.night.b,
      }),
      ...title(i.title, 300, { size: 15, weight: 600, color: P.night.c, letterSpacing: 1 }),
      ...nameLine(i.name, 340, P.night.a, 24),
    ],
  }),
  def({
    id: 'bday-funny-candles',
    title: 'So many candles',
    occasions: ['birthday'],
    tags: ['funny', 'for him', 'for her'],
    supportsPhoto: false,
    tint: 'butter',
    palette: 'butter',
    scene: (i) => [
      ...bg(P.butter.bg),
      ...Array.from({ length: 11 }, (_, k) =>
        candle(
          34 + k * 19.6,
          236,
          26 + ((k * 7) % 3) * 10,
          [P.butter.b, P.butter.c, P.butter.d, '#FFFFFF'][k % 4] ?? '#fff',
        ),
      ).flat(),
      { tag: 'rect', attrs: { x: 22, y: 236, width: W - 44, height: 30, rx: 6, fill: P.butter.b } },
      { tag: 'rect', attrs: { x: 30, y: 258, width: W - 60, height: 26, rx: 6, fill: '#FFFFFF' } },
      ...title('Careful,', 60, { font: 'hand', size: 40, weight: 700, color: P.butter.ink }),
      ...title("that's a fire hazard.", 96, {
        font: 'hand',
        size: 30,
        weight: 500,
        color: P.butter.ink,
      }),
      ...title(i.title, 322, { size: 15, weight: 600, color: P.butter.ink, letterSpacing: 1 }),
      ...nameLine(i.name, 352, P.butter.b, 22),
    ],
  }),
  def({
    id: 'bday-balloons-sky',
    title: 'Up and away',
    occasions: ['birthday'],
    tags: ['cute', 'for kids'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'ocean',
    scene: (i) => [
      ...bg(P.ocean.bg),
      ...cloud(52, 300, 90, '#FFFFFF'),
      ...cloud(200, 320, 110, '#FFFFFF'),
      ...cloud(140, 90, 60, '#FFFFFF'),
      ...balloon(70, 150, 26, P.ocean.d, 110, 7),
      ...balloon(132, 110, 32, P.ocean.c, 130, -8),
      ...balloon(196, 160, 24, P.ocean.a, 100, 6),
      ...titleLines(twoLines(i.title), 34, 26, { size: 22, color: P.ocean.ink }),
      ...nameLine(i.name, 352, P.ocean.a, 22),
      { tag: 'rect', attrs: { x: 0, y: H - 6, width: W, height: 6, fill: P.ocean.a } },
    ],
  }),
];
