import {
  arch,
  bauble,
  bg,
  crescent,
  diya,
  dreidel,
  firework,
  frame,
  holly,
  lantern,
  menorah,
  nameLine,
  PALETTES,
  photoFrame,
  rangoli,
  snow,
  sparkles,
  star5,
  star8,
  starOfDavid,
  title,
  titleLines,
  tree,
  twoLines,
  wreath,
} from '../primitives';
import { H, W } from '../scene';
import { def, type DesignDef } from '../types';

const P = PALETTES;

export const celebrations: DesignDef[] = [
  def({
    id: 'eid-crescent',
    title: 'Crescent moon',
    occasions: ['eid'],
    tags: ['minimal'],
    supportsPhoto: false,
    tint: 'mint',
    palette: 'night',
    scene: (i) => [
      ...bg(P.night.bg),
      ...sparkles(51, 30, P.night.a, { x: 10, y: 10, w: W - 20, h: 250 }, 3.5),
      ...crescent(140, 140, 72, P.night.a, P.night.bg),
      ...star5(80, 90, 8, P.night.b),
      ...star5(210, 210, 6, P.night.b),
      ...titleLines(twoLines(i.title), 300, 32, { size: 30, color: P.night.b }),
      ...nameLine(i.name, 352, P.night.a),
    ],
  }),
  def({
    id: 'eid-lanterns',
    title: 'Lantern lights',
    occasions: ['eid'],
    tags: ['cute'],
    supportsPhoto: false,
    tint: 'lilac',
    palette: 'plum',
    scene: (i) => [
      ...bg(P.plum.bg),
      ...sparkles(61, 22, P.plum.a, undefined, 3),
      ...lantern(60, 40, 110, P.plum.a, P.plum.b),
      ...lantern(132, 20, 140, P.plum.a, P.plum.c),
      ...lantern(204, 50, 100, P.plum.a, P.plum.d),
      ...titleLines(twoLines(i.title), 286, 32, { size: 30, color: P.plum.ink }),
      ...nameLine(i.name, 340, P.plum.a),
    ],
  }),
  def({
    id: 'eid-arch',
    title: 'Geometric arch',
    occasions: ['eid'],
    tags: ['minimal'],
    supportsPhoto: false,
    tint: 'mint',
    palette: 'mint',
    scene: (i) => [
      ...bg(P.mint.bg),
      ...arch(W / 2, 40, 168, 210, P.mint.a),
      ...arch(W / 2, 58, 136, 192, P.mint.bg),
      ...star8(W / 2, 150, 34, P.mint.c),
      ...star8(W / 2, 150, 16, '#FFFFFF'),
      ...crescent(W / 2, 90, 16, P.mint.a, P.mint.bg),
      ...titleLines(twoLines(i.title), 292, 30, { size: 28, color: P.mint.ink }),
      ...nameLine(i.name, 346, P.mint.a),
    ],
  }),
  def({
    id: 'diwali-diyas',
    title: 'Row of diyas',
    occasions: ['diwali'],
    tags: ['cute'],
    supportsPhoto: false,
    tint: 'butter',
    palette: 'plum',
    scene: (i) => [
      ...bg(P.plum.bg),
      ...sparkles(71, 24, P.plum.a, { x: 10, y: 10, w: W - 20, h: 150 }, 3.5),
      ...diya(66, 240, 54, '#B5462E', P.plum.a),
      ...diya(132, 250, 68, '#B5462E', P.plum.a),
      ...diya(198, 240, 54, '#B5462E', P.plum.a),
      {
        tag: 'rect',
        attrs: { x: 30, y: 250, width: W - 60, height: 4, rx: 2, fill: P.plum.a, opacity: 0.6 },
      },
      ...titleLines(twoLines(i.title), 300, 32, { size: 30, color: P.plum.ink }),
      ...nameLine(i.name, 352, P.plum.a),
    ],
  }),
  def({
    id: 'diwali-rangoli',
    title: 'Rangoli',
    occasions: ['diwali'],
    tags: ['floral'],
    supportsPhoto: false,
    tint: 'butter',
    palette: 'butter',
    scene: (i) => [
      ...bg(P.butter.bg),
      ...rangoli(W / 2, 156, 100, [P.butter.a, P.butter.b, '#6C4BD3', P.butter.d, '#FF8FA3']),
      ...titleLines(twoLines(i.title), 300, 30, { size: 28, color: P.butter.ink }),
      ...nameLine(i.name, 352, P.butter.b),
    ],
  }),
  def({
    id: 'diwali-fireworks',
    title: 'Festival of lights',
    occasions: ['diwali'],
    tags: ['funny', 'for kids'],
    supportsPhoto: false,
    tint: 'lilac',
    palette: 'night',
    scene: (i) => [
      ...bg(P.night.bg),
      ...firework(70, 90, 40, P.night.a, 12),
      ...firework(190, 70, 30, P.night.d, 10),
      ...firework(150, 170, 52, P.night.c, 14),
      ...firework(60, 220, 26, P.night.b, 8),
      ...diya(W / 2, 290, 60, '#B5462E', P.night.a),
      ...titleLines(twoLines(i.title), 316, 28, { size: 26, color: P.night.b }),
      ...nameLine(i.name, 358, P.night.a, 22),
    ],
  }),
  def({
    id: 'hanukkah-menorah',
    title: 'Menorah glow',
    occasions: ['hanukkah'],
    tags: ['minimal'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'sky',
    scene: (i) => [
      ...bg(P.sky.bg),
      ...sparkles(81, 14, P.sky.d, { x: 20, y: 20, w: W - 40, h: 120 }, 4),
      ...menorah(W / 2, 250, P.sky.a, P.sky.d),
      ...titleLines(twoLines(i.title), 300, 30, { size: 28, color: P.sky.ink }),
      ...nameLine(i.name, 352, P.sky.a),
    ],
  }),
  def({
    id: 'hanukkah-dreidels',
    title: 'Dreidels',
    occasions: ['hanukkah'],
    tags: ['cute', 'for kids'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'paper',
    scene: (i) => [
      ...bg(P.paper.bg),
      ...frame(P.paper.c, 14, 6, 2),
      ...dreidel(84, 150, 56, P.paper.c, '#FFFFFF'),
      ...dreidel(176, 170, 62, '#8FB0FF', P.paper.c),
      ...star5(56, 70, 7, P.paper.b),
      ...star5(212, 96, 6, P.paper.b),
      ...titleLines(twoLines(i.title), 286, 30, { size: 28, color: P.paper.c }),
      ...nameLine(i.name, 340, P.paper.ink),
    ],
  }),
  def({
    id: 'hanukkah-star',
    title: 'Eight nights',
    occasions: ['hanukkah'],
    tags: ['minimal'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'night',
    scene: (i) => [
      ...bg(P.night.bg),
      ...sparkles(91, 24, P.night.c, undefined, 3.5),
      ...starOfDavid(W / 2, 140, 76, P.night.a, 6),
      ...title('eight nights of light', 250, {
        font: 'hand',
        size: 30,
        weight: 700,
        color: P.night.b,
      }),
      ...titleLines(twoLines(i.title), 300, 28, { size: 24, color: P.night.c }),
      ...nameLine(i.name, 352, P.night.a),
    ],
  }),
  def({
    id: 'xmas-tree',
    title: 'Tree and baubles',
    occasions: ['christmas'],
    tags: ['cute'],
    supportsPhoto: false,
    tint: 'mint',
    palette: 'forest',
    scene: (i) => [
      ...bg(P.forest.bg),
      ...snow(101, 40, '#FFFFFF', 0.8),
      ...tree(W / 2, 250, 190, P.forest.d),
      ...star5(W / 2, 62, 12, P.forest.a),
      ...bauble(112, 150, 8, P.forest.b),
      ...bauble(156, 190, 9, P.forest.a),
      ...bauble(122, 226, 8, P.forest.c),
      ...bauble(168, 118, 7, P.forest.b),
      ...titleLines(twoLines(i.title), 300, 30, { size: 28, color: P.forest.ink }),
      ...nameLine(i.name, 352, P.forest.a),
    ],
  }),
  def({
    id: 'xmas-snowfall',
    title: 'Snowfall',
    occasions: ['christmas'],
    tags: ['minimal', 'cute'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'sky',
    scene: (i) => [
      ...bg(P.sky.bg),
      {
        tag: 'path',
        attrs: {
          d: `M0 ${H} L0 270 Q66 240 132 262 Q198 284 ${W} 250 L${W} ${H}Z`,
          fill: '#FFFFFF',
        },
      },
      ...tree(58, 270, 80, P.sky.a, '#3A2E12'),
      ...tree(132, 266, 110, '#1B7A5A', '#3A2E12'),
      ...tree(206, 272, 76, P.sky.a, '#3A2E12'),
      ...snow(111, 60, '#FFFFFF', 0.95),
      ...titleLines(twoLines(i.title), 60, 30, { size: 28, color: P.sky.ink }),
      ...nameLine(i.name, 340, P.sky.ink, 24),
    ],
  }),
  def({
    id: 'xmas-holly-wreath',
    title: 'Holly wreath',
    occasions: ['christmas'],
    tags: ['floral'],
    supportsPhoto: false,
    tint: 'mint',
    palette: 'paper',
    scene: (i) => [
      ...bg(P.paper.bg),
      ...wreath(W / 2, 160, 88, '#1B7A5A', P.paper.a, 20),
      ...holly(W / 2, 236, 22),
      ...titleLines(twoLines(i.title), 138, 30, { size: 24, color: P.paper.ink }),
      ...nameLine(i.name, 190, P.paper.a),
      ...snow(121, 20, '#8FB0FF', 0.5),
    ],
  }),
  def({
    id: 'xmas-photo',
    title: 'Christmas photo',
    occasions: ['christmas'],
    tags: ['photo upload'],
    supportsPhoto: true,
    tint: 'mint',
    palette: 'forest',
    scene: (i) => [
      ...bg(P.forest.bg),
      ...snow(131, 30, '#FFFFFF', 0.6),
      ...photoFrame(40, 44, W - 80, 196, '#FFFFFF'),
      ...holly(52, 50, 18, P.forest.d, P.forest.b),
      ...holly(W - 52, 236, 18, P.forest.d, P.forest.b),
      ...titleLines(twoLines(i.title), 294, 28, { size: 26, color: P.forest.ink }),
      ...nameLine(i.name, 346, P.forest.a),
    ],
  }),
];
