import {
  bg,
  confetti,
  dots,
  flower,
  frame,
  heart,
  leafSprig,
  nameLine,
  PALETTES,
  photoFrame,
  scallop,
  sparkle,
  sparkles,
  title,
  titleLines,
  tulip,
  twoLines,
  wreath,
} from '../primitives';
import { H, W, type Shape } from '../scene';
import { def, type DesignDef } from '../types';

const P = PALETTES;

const glass = (cx: number, baseY: number, h: number, color: string, fizz: string): Shape[] => [
  {
    tag: 'path',
    attrs: {
      d: `M${cx - 4} ${baseY} L${cx + 4} ${baseY} L${cx + 14} ${baseY + 6} L${cx - 14} ${baseY + 6}z`,
      fill: color,
    },
  },
  {
    tag: 'rect',
    attrs: { x: cx - 1.5, y: baseY - h * 0.45, width: 3, height: h * 0.45, fill: color },
  },
  {
    tag: 'path',
    attrs: {
      d: `M${cx - 14} ${baseY - h} L${cx + 14} ${baseY - h} L${cx + 10} ${baseY - h * 0.45} L${cx - 10} ${baseY - h * 0.45}z`,
      fill: fizz,
      opacity: 0.85,
    },
  },
  {
    tag: 'path',
    attrs: {
      d: `M${cx - 14} ${baseY - h} L${cx + 14} ${baseY - h} L${cx + 10} ${baseY - h * 0.45} L${cx - 10} ${baseY - h * 0.45}z`,
      fill: 'none',
      stroke: color,
      strokeWidth: 1.5,
    },
  },
  { tag: 'circle', attrs: { cx: cx - 4, cy: baseY - h * 0.8, r: 2, fill: '#FFFFFF' } },
  { tag: 'circle', attrs: { cx: cx + 5, cy: baseY - h * 0.65, r: 1.6, fill: '#FFFFFF' } },
];

export const family: DesignDef[] = [
  def({
    id: 'anniv-two-hearts',
    title: 'Two hearts',
    occasions: ['anniversary'],
    tags: ['minimal', 'cute'],
    supportsPhoto: false,
    tint: 'blush',
    palette: 'blush',
    scene: (i) => [
      ...bg(P.blush.bg),
      ...dots(P.blush.b, 6, 9, 2, 0.35),
      ...heart(112, 150, 110, P.blush.a),
      ...heart(160, 176, 84, P.blush.b),
      ...sparkle(60, 100, 9, P.blush.d),
      ...sparkle(206, 122, 7, P.blush.d),
      ...titleLines(twoLines(i.title), 292, 30, { size: 28, color: P.blush.c }),
      ...nameLine(i.name, 346, P.blush.a),
    ],
  }),
  def({
    id: 'anniv-wreath',
    title: 'Anniversary wreath',
    occasions: ['anniversary'],
    tags: ['floral', 'for her'],
    supportsPhoto: false,
    tint: 'mint',
    palette: 'mint',
    scene: (i) => [
      ...bg(P.mint.bg),
      ...wreath(W / 2, 160, 92, P.mint.a, P.mint.d, 20),
      ...heart(W / 2, 160, 46, P.mint.d),
      ...titleLines(twoLines(i.title), 300, 30, { size: 28, color: P.mint.ink }),
      ...nameLine(i.name, 352, P.mint.a),
    ],
  }),
  def({
    id: 'anniv-champagne',
    title: 'Cheers to you two',
    occasions: ['anniversary'],
    tags: ['funny', 'for him', 'for her'],
    supportsPhoto: false,
    tint: 'butter',
    palette: 'paper',
    scene: (i) => [
      ...bg(P.paper.bg),
      ...confetti(17, 22, [P.paper.b, P.paper.a, P.paper.c], { x: 20, y: 20, w: W - 40, h: 130 }),
      ...glass(104, 258, 120, P.paper.ink, P.paper.b),
      ...glass(164, 258, 120, P.paper.ink, P.paper.b),
      ...title('Cheers', 80, { font: 'hand', size: 54, weight: 700, color: P.paper.a }),
      ...title('to you two', 118, { font: 'hand', size: 30, weight: 500, color: P.paper.ink }),
      ...title(i.title, 318, { size: 14, weight: 600, color: P.paper.ink, letterSpacing: 1 }),
      ...nameLine(i.name, 350, P.paper.c, 22),
    ],
  }),
  def({
    id: 'anniv-photo',
    title: 'Our year in a photo',
    occasions: ['anniversary'],
    tags: ['photo upload'],
    supportsPhoto: true,
    tint: 'blush',
    palette: 'sand',
    scene: (i) => [
      ...bg(P.sand.bg),
      ...photoFrame(40, 40, W - 80, 200, '#FFFFFF'),
      ...heart(W - 44, 232, 34, P.sand.a),
      ...leafSprig(26, 372, 54, 152, P.sand.c, 3),
      ...titleLines(twoLines(i.title), 292, 28, { size: 26, color: P.sand.ink }),
      ...nameLine(i.name, 344, P.sand.a),
    ],
  }),
  def({
    id: 'mum-tulips',
    title: 'Tulips for Mum',
    occasions: ['mothers_day'],
    tags: ['floral', 'for her'],
    supportsPhoto: false,
    tint: 'blush',
    palette: 'blush',
    scene: (i) => [
      ...bg(P.blush.bg),
      ...scallop('#FFFFFF', 64, 14, true),
      ...titleLines(twoLines(i.title), 30, 26, { size: 22, color: P.blush.a }),
      ...tulip(78, 300, 170, P.blush.a),
      ...tulip(132, 310, 200, P.blush.d),
      ...tulip(186, 300, 170, P.blush.b),
      {
        tag: 'path',
        attrs: { d: `M${W / 2 - 40} 300 q40 -12 80 0 q-40 22 -80 0z`, fill: P.blush.c },
      },
      ...nameLine(i.name, 348, P.blush.c, 24),
    ],
  }),
  def({
    id: 'mum-floral-frame',
    title: 'Floral frame',
    occasions: ['mothers_day', 'womens_day'],
    tags: ['floral', 'for her'],
    supportsPhoto: false,
    tint: 'lilac',
    palette: 'paper',
    scene: (i) => [
      ...bg(P.paper.bg),
      ...Array.from({ length: 10 }, (_, k) => {
        const a = (k / 10) * Math.PI * 2;
        return flower(
          W / 2 + Math.cos(a) * 96,
          178 + Math.sin(a) * 118,
          16 + (k % 3) * 4,
          5 + (k % 2),
          [P.paper.a, '#FF8FA3', P.paper.b, '#B39DFF'][k % 4] ?? P.paper.a,
          '#FFFFFF',
        );
      }).flat(),
      ...Array.from({ length: 10 }, (_, k) => {
        const a = (k / 10) * Math.PI * 2 + 0.3;
        return leafSprig(
          W / 2 + Math.cos(a) * 118,
          178 + Math.sin(a) * 140,
          28,
          (a * 180) / Math.PI + 90,
          P.paper.d,
          3,
        );
      }).flat(),
      ...titleLines(twoLines(i.title), 166, 28, { size: 22, color: P.paper.ink }),
      ...nameLine(i.name, 218, P.paper.a, 22),
    ],
  }),
  def({
    id: 'mum-heart-bouquet',
    title: 'Heart of flowers',
    occasions: ['mothers_day'],
    tags: ['floral', 'cute', 'for her'],
    supportsPhoto: false,
    tint: 'butter',
    palette: 'butter',
    scene: (i) => [
      ...bg(P.butter.bg),
      ...heart(W / 2, 150, 150, '#FFFFFF'),
      ...[
        [96, 110],
        [132, 96],
        [168, 110],
        [86, 150],
        [132, 140],
        [178, 150],
        [104, 190],
        [160, 190],
        [132, 222],
      ].flatMap(([x, y], k) =>
        flower(
          x ?? 0,
          y ?? 0,
          15,
          6,
          [P.butter.b, '#FF8FA3', P.butter.a, '#B39DFF'][k % 4] ?? P.butter.a,
          k % 2 ? '#FFFFFF' : P.butter.a,
        ),
      ),
      ...titleLines(twoLines(i.title), 300, 30, { size: 28, color: P.butter.ink }),
      ...nameLine(i.name, 352, P.butter.b),
    ],
  }),
  def({
    id: 'mum-photo',
    title: 'Mum and me',
    occasions: ['mothers_day'],
    tags: ['photo upload', 'for her'],
    supportsPhoto: true,
    tint: 'lilac',
    palette: 'lilac',
    scene: (i) => [
      ...bg(P.lilac.bg),
      ...photoFrame(44, 48, W - 88, 190, '#FFFFFF'),
      ...flower(44, 52, 20, 6, P.lilac.d, '#FFFFFF'),
      ...flower(W - 44, 238, 22, 6, P.lilac.c, '#FFFFFF'),
      ...titleLines(twoLines(i.title), 292, 28, { size: 26, color: P.lilac.ink }),
      ...nameLine(i.name, 344, P.lilac.a),
    ],
  }),
  def({
    id: 'iwd-bold-type',
    title: 'Strong, kind, you',
    occasions: ['womens_day'],
    tags: ['minimal', 'for her'],
    supportsPhoto: false,
    tint: 'lilac',
    palette: 'lilac',
    scene: (i) => [
      ...bg(P.lilac.a),
      {
        tag: 'rect',
        attrs: { x: 22, y: 22, width: W - 44, height: H - 44, rx: 12, fill: P.lilac.bg },
      },
      ...title('Strong.', 120, { size: 44, color: P.lilac.a, anchor: 'start', x: 40 }),
      ...title('Kind.', 168, { size: 44, color: P.lilac.d, anchor: 'start', x: 40 }),
      ...title('You.', 216, { size: 44, color: P.lilac.ink, anchor: 'start', x: 40 }),
      ...title(i.title, 300, {
        size: 14,
        weight: 600,
        color: P.lilac.ink,
        letterSpacing: 1,
        anchor: 'start',
        x: 40,
      }),
      ...(i.name
        ? title(i.name, 332, {
            font: 'hand',
            size: 24,
            weight: 700,
            color: P.lilac.a,
            anchor: 'start',
            x: 40,
          })
        : []),
    ],
  }),
  def({
    id: 'iwd-blooms',
    title: 'Blooms for her',
    occasions: ['womens_day', 'mothers_day'],
    tags: ['floral', 'for her'],
    supportsPhoto: false,
    tint: 'mint',
    palette: 'mint',
    scene: (i) => [
      ...bg(P.mint.bg),
      ...leafSprig(60, 360, 150, 20, P.mint.a, 6),
      ...leafSprig(204, 360, 150, -20, P.mint.a, 6),
      ...leafSprig(132, 350, 130, 0, P.mint.a, 5),
      ...flower(84, 208, 26, 7, P.mint.d, P.mint.c),
      ...flower(132, 190, 30, 8, P.mint.c, '#FFFFFF'),
      ...flower(180, 208, 26, 7, '#FF8FA3', P.mint.c),
      ...titleLines(twoLines(i.title), 66, 30, { size: 26, color: P.mint.ink }),
      ...nameLine(i.name, 122, P.mint.a),
    ],
  }),
  def({
    id: 'iwd-mirror-hearts',
    title: 'Here for you',
    occasions: ['womens_day', 'anniversary'],
    tags: ['cute', 'minimal'],
    supportsPhoto: false,
    tint: 'blush',
    palette: 'blush',
    scene: (i) => [
      ...bg('#FFFFFF'),
      ...frame(P.blush.a, 14, 6, 3),
      ...heart(92, 150, 70, P.blush.b),
      ...heart(172, 150, 70, P.blush.a),
      ...sparkles(41, 8, P.blush.d, { x: 40, y: 60, w: W - 80, h: 180 }, 5),
      ...title('Here for you,', 258, { font: 'hand', size: 32, weight: 700, color: P.blush.c }),
      ...title('always.', 292, { font: 'hand', size: 32, weight: 700, color: P.blush.a }),
      ...nameLine(i.name, 340, P.blush.c, 22),
    ],
  }),
];
