import {
  banner,
  bg,
  cloud,
  confetti,
  dots,
  envelope,
  flower,
  frame,
  heart,
  hills,
  laurel,
  leafSprig,
  nameLine,
  numeral,
  PALETTES,
  paperPlane,
  speechBubble,
  sparkles,
  suitcase,
  sun,
  title,
  titleLines,
  trophy,
  twoLines,
  wreath,
} from '../primitives';
import { H, W, type Shape } from '../scene';
import { def, type DesignDef } from '../types';

const P = PALETTES;

const clover = (cx: number, cy: number, s: number, color: string): Shape[] => [
  ...heart(cx, cy - s * 0.5, s, color).map((h) => ({
    ...h,
    attrs: { ...h.attrs, transform: `${h.attrs.transform} rotate(0)` },
  })),
  {
    tag: 'path',
    attrs: {
      d: 'M0 40 C-60 -10 -40 -60 0 -28 C40 -60 60 -10 0 40z',
      fill: color,
      transform: `translate(${cx + s * 0.5} ${cy}) rotate(90) scale(${s / 60})`,
    },
  },
  {
    tag: 'path',
    attrs: {
      d: 'M0 40 C-60 -10 -40 -60 0 -28 C40 -60 60 -10 0 40z',
      fill: color,
      transform: `translate(${cx} ${cy + s * 0.5}) rotate(180) scale(${s / 60})`,
    },
  },
  {
    tag: 'path',
    attrs: {
      d: 'M0 40 C-60 -10 -40 -60 0 -28 C40 -60 60 -10 0 40z',
      fill: color,
      transform: `translate(${cx - s * 0.5} ${cy}) rotate(270) scale(${s / 60})`,
    },
  },
  {
    tag: 'path',
    attrs: {
      d: `M${cx} ${cy + s * 0.4} q-8 ${s * 0.6} 4 ${s * 1.1}`,
      stroke: color,
      strokeWidth: 3,
      fill: 'none',
      strokeLinecap: 'round',
    },
  },
];

export const work: DesignDef[] = [
  def({
    id: 'thanks-script',
    title: 'Thank you, script',
    occasions: ['thank_you'],
    tags: ['minimal'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'paper',
    scene: (i) => [
      ...bg(P.paper.bg),
      ...frame(P.paper.ink, 14, 4, 1.5),
      ...title('thank', 168, { font: 'hand', size: 60, weight: 700, color: P.paper.ink }),
      ...title('you', 226, { font: 'hand', size: 68, weight: 700, color: P.paper.a }),
      ...sparkles(131, 6, P.paper.b, { x: 40, y: 80, w: W - 80, h: 170 }, 6),
      ...nameLine(i.name, 300, P.paper.c, 22),
    ],
  }),
  def({
    id: 'thanks-wreath',
    title: 'Grateful wreath',
    occasions: ['thank_you'],
    tags: ['floral'],
    supportsPhoto: false,
    tint: 'mint',
    palette: 'mint',
    scene: (i) => [
      ...bg(P.mint.bg),
      ...wreath(W / 2, 168, 90, P.mint.a, P.mint.c, 20),
      ...flower(W / 2 - 60, 112, 14, 6, P.mint.d, '#FFFFFF'),
      ...flower(W / 2 + 62, 224, 14, 6, '#FF8FA3', '#FFFFFF'),
      ...titleLines(twoLines(i.title), 158, 30, { size: 26, color: P.mint.ink }),
      ...nameLine(i.name, 208, P.mint.a),
    ],
  }),
  def({
    id: 'thanks-speech',
    title: 'Big thank you',
    occasions: ['thank_you'],
    tags: ['funny', 'cute'],
    supportsPhoto: false,
    tint: 'butter',
    palette: 'butter',
    scene: (i) => [
      ...bg(P.butter.bg),
      ...dots(P.butter.a, 6, 9, 2, 0.2),
      ...speechBubble(30, 70, W - 60, 130, '#FFFFFF'),
      ...title('THANK', 128, { size: 40, color: P.butter.ink, letterSpacing: 2 }),
      ...title('YOU!', 174, { size: 44, color: P.butter.b, letterSpacing: 2 }),
      ...title('(seriously, thank you)', 262, {
        font: 'hand',
        size: 26,
        weight: 500,
        color: P.butter.ink,
      }),
      ...nameLine(i.name, 320, P.butter.b, 22),
    ],
  }),
  def({
    id: 'thanks-envelope',
    title: 'A note of thanks',
    occasions: ['thank_you'],
    tags: ['cute', 'minimal'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'sky',
    scene: (i) => [
      ...bg(P.sky.bg),
      ...envelope(W / 2, 156, 160, '#FFFFFF', P.sky.b),
      ...heart(W / 2, 172, 34, P.sky.c),
      ...sparkles(141, 10, P.sky.d, { x: 20, y: 40, w: W - 40, h: 200 }, 5),
      ...titleLines(twoLines(i.title), 286, 30, { size: 28, color: P.sky.ink }),
      ...nameLine(i.name, 340, P.sky.a),
    ],
  }),
  def({
    id: 'leaving-sunrise',
    title: 'New horizons',
    occasions: ['leaving'],
    tags: ['minimal', 'for him', 'for her'],
    supportsPhoto: false,
    tint: 'butter',
    palette: 'coral',
    scene: (i) => [
      ...bg(P.coral.bg),
      ...sun(W / 2, 166, 44, P.coral.b, 14, '#FFD166'),
      ...hills(230, ['#F9C9B6', P.coral.a, '#B8442F']),
      ...title('Good luck', 70, { size: 34, color: P.coral.ink }),
      ...title('on the next adventure', 98, {
        font: 'hand',
        size: 26,
        weight: 500,
        color: P.coral.ink,
      }),
      ...nameLine(i.name, 340, '#FFFFFF', 26),
    ],
  }),
  def({
    id: 'leaving-suitcase',
    title: 'Packed and ready',
    occasions: ['leaving'],
    tags: ['funny', 'cute'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'sky',
    scene: (i) => [
      ...bg(P.sky.bg),
      ...cloud(60, 70, 70, '#FFFFFF'),
      ...cloud(200, 100, 90, '#FFFFFF'),
      ...suitcase(W / 2, 200, 150, P.sky.c, P.sky.ink),
      ...confetti(151, 16, [P.sky.a, P.sky.d, '#FFFFFF'], { x: 20, y: 120, w: W - 40, h: 160 }),
      ...title("We'll miss you", 306, { font: 'hand', size: 34, weight: 700, color: P.sky.ink }),
      ...title(i.title, 334, { size: 14, weight: 600, color: P.sky.a, letterSpacing: 1 }),
      ...nameLine(i.name, 360, P.sky.ink, 20),
    ],
  }),
  def({
    id: 'leaving-plane',
    title: 'Off you go',
    occasions: ['leaving'],
    tags: ['minimal', 'for him'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'ocean',
    scene: (i) => [
      ...bg(P.ocean.bg),
      ...cloud(70, 250, 100, '#FFFFFF'),
      ...cloud(190, 290, 130, '#FFFFFF'),
      ...paperPlane(150, 120, 58, '#FFFFFF', P.ocean.b),
      {
        tag: 'path',
        attrs: {
          d: 'M30 200 q40 -40 70 -20 q30 20 50 -20',
          stroke: P.ocean.a,
          strokeWidth: 2,
          fill: 'none',
          strokeDasharray: '5 5',
          opacity: 0.6,
        },
      },
      ...title('Off you go!', 58, { size: 32, color: P.ocean.ink }),
      ...title(i.title, 84, { size: 14, weight: 600, color: P.ocean.a, letterSpacing: 1 }),
      ...nameLine(i.name, 348, P.ocean.ink, 24),
    ],
  }),
  def({
    id: 'leaving-clover',
    title: 'Good luck clover',
    occasions: ['leaving'],
    tags: ['cute', 'minimal'],
    supportsPhoto: false,
    tint: 'mint',
    palette: 'mint',
    scene: (i) => [
      ...bg(P.mint.bg),
      ...dots('#FFFFFF', 6, 9, 3, 0.8),
      ...clover(W / 2, 150, 66, P.mint.a),
      ...title(i.title, 286, { size: 34, color: P.mint.ink }),
      ...title('in everything next', 316, {
        font: 'hand',
        size: 26,
        weight: 500,
        color: P.mint.ink,
      }),
      ...nameLine(i.name, 354, P.mint.a, 22),
    ],
  }),
  def({
    id: 'work-laurel',
    title: 'Laurel years',
    occasions: ['work_anniversary'],
    tags: ['minimal', 'milestone'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'paper',
    scene: (i) => [
      ...bg(P.paper.bg),
      ...laurel(W / 2, 150, 92, P.paper.d),
      ...numeral(i.age, 174, 84, P.paper.ink, '★'),
      ...title(i.age === 1 ? 'year' : 'years', 208, {
        size: 16,
        weight: 600,
        color: P.paper.d,
        letterSpacing: 2,
      }),
      ...titleLines(twoLines(i.title), 292, 28, { size: 24, color: P.paper.ink }),
      ...nameLine(i.name, 344, P.paper.a, 22),
    ],
  }),
  def({
    id: 'work-trophy',
    title: 'Team trophy',
    occasions: ['work_anniversary'],
    tags: ['funny', 'for him', 'for her'],
    supportsPhoto: false,
    tint: 'butter',
    palette: 'butter',
    scene: (i) => [
      ...bg(P.butter.bg),
      ...confetti(161, 30, [P.butter.a, P.butter.b, P.butter.c, '#FFFFFF'], {
        x: 10,
        y: 10,
        w: W - 20,
        h: 140,
      }),
      ...trophy(W / 2, 250, 150, P.butter.a, '#B08D57'),
      ...banner(W / 2, 296, 190, 34, P.butter.c, i.title, '#FFFFFF', 13),
      ...nameLine(i.name, 350, P.butter.ink, 24),
    ],
  }),
  def({
    id: 'work-confetti-years',
    title: 'Confetti years',
    occasions: ['work_anniversary', 'birthday'],
    tags: ['milestone', 'funny'],
    supportsPhoto: false,
    tint: 'sky',
    palette: 'sky',
    scene: (i) => [
      ...bg(P.sky.bg),
      ...confetti(171, 46, [P.sky.a, P.sky.c, P.sky.d, '#FFFFFF']),
      { tag: 'circle', attrs: { cx: W / 2, cy: 160, r: 92, fill: '#FFFFFF' } },
      ...numeral(i.age, 190, 96, P.sky.a, '★'),
      ...title('years of you', 226, { font: 'hand', size: 26, weight: 700, color: P.sky.ink }),
      ...titleLines(twoLines(i.title), 300, 26, { size: 22, color: P.sky.ink }),
      ...nameLine(i.name, 348, P.sky.a, 22),
    ],
  }),
  def({
    id: 'thanks-sprigs',
    title: 'Sprigs of thanks',
    occasions: ['thank_you', 'mothers_day'],
    tags: ['floral', 'minimal'],
    supportsPhoto: false,
    tint: 'mint',
    palette: 'sand',
    scene: (i) => [
      ...bg(P.sand.bg),
      ...leafSprig(40, H - 20, 150, 25, P.sand.c, 6),
      ...leafSprig(W - 40, H - 20, 150, -25, P.sand.c, 6),
      ...flower(64, 236, 16, 6, P.sand.a, P.sand.b),
      ...flower(W - 64, 236, 16, 6, P.sand.b, P.sand.a),
      ...titleLines(twoLines(i.title), 120, 34, { size: 30, color: P.sand.ink }),
      ...nameLine(i.name, 180, P.sand.a, 24),
    ],
  }),
];
