/**
 * Generates docs/pricing.md from src/domain/constants.ts through quote() and the economics
 * functions, so the document can never disagree with the code. Run with `pnpm docs:pricing`;
 * CI fails when the checked-in file differs from the generated one.
 */
import { writeFileSync } from 'node:fs';

import prettier from 'prettier';

import {
  BLEND,
  BUSINESS,
  BUSINESS_COSTS,
  DEFAULT_COSTS,
  DIGITAL,
  FINISHES,
  FIRST_CARD_FREE,
  FLORIST,
  GIFTS,
  GIFT_COST_SHARE,
  GUARANTEE,
  MODES,
  MOONPIG,
  PICKUP,
  PICKUP_PROMISE,
  PRICE,
  PRINT_COST,
  SIZES,
  STAMPS,
  allowedModes,
  annualCalculator,
  businessUnitContributionPence,
  businessUnitPricePence,
  chooseMode,
  economics,
  expectedCommissionPence,
  formatPence,
  priceBatch,
  quote,
  toPence,
  type Finish,
  type PrintedMode,
  type Size,
} from '../src/domain';
import type { QuoteInput } from '../src/domain/pricing';

const sizes = Object.keys(SIZES) as Size[];
const finishes = Object.keys(FINISHES) as Finish[];
const gbp = (pounds: number) => formatPence(toPence(pounds));
const p = (pence: number) => formatPence(pence);
const pct = (share: number) => `${Math.round(share * 100)}%`;

const out: string[] = [];
const line = (s = '') => out.push(s);
const table = (head: string[], rows: string[][]) => {
  line(`| ${head.join(' | ')} |`);
  line(`| ${head.map(() => '---').join(' | ')} |`);
  for (const r of rows) line(`| ${r.join(' | ')} |`);
  line();
};

line('# Pricing');
line();
line(
  'Generated by `pnpm docs:pricing` from `src/domain/constants.ts` through `quote()`, `economics()` and the business and florist functions. Do not edit by hand: change the constants and regenerate. Consumer prices include VAT at 20% (ex VAT = total / 1.2); business prices exclude VAT. Money is integer pence inside the domain, rounded half up once at the end of each calculation.',
);
line();

line('## 1. Card prices, including VAT');
line();
table(
  ['Size', ...finishes.map((f) => FINISHES[f].label)],
  sizes.map((s) => [SIZES[s].label, ...finishes.map((f) => gbp(PRICE[s][f]))]),
);

line('## 2. Print cost, excluding VAT');
line();
table(
  ['Size', ...finishes.map((f) => FINISHES[f].label)],
  sizes.map((s) => [SIZES[s].label, ...finishes.map((f) => gbp(PRINT_COST[s][f]))]),
);

line('## 3. Delivery');
line();
const modeRows = (['advance', 'tracked', 'pickup'] as PrintedMode[]).map((m) => {
  const price = MODES[m].price as Partial<Record<Size, number>>;
  const cost = MODES[m].cost as Partial<Record<Size, number>>;
  const cell = (v: number | undefined, fallback: string) => (v == null ? fallback : gbp(v));
  return [
    MODES[m].label,
    ...sizes.map((s) => cell(price[s], 'not offered')),
    ...sizes.map((s) =>
      m === 'pickup' && s === 'regular' ? 'see rule 4' : cell(cost[s], 'not offered'),
    ),
    MODES[m].guarantee ? 'yes' : 'no',
  ];
});
table(
  [
    'Mode',
    ...sizes.map((s) => `Price ${SIZES[s].label}`),
    ...sizes.map((s) => `Cost ${SIZES[s].label}`),
    'Guarantee',
  ],
  modeRows,
);
line('eCards have no delivery line.');
line();

line('## 4. Pick-up');
line();
line(
  `- Offered only for ${PICKUP.sizes.map((s) => SIZES[s].label).join(', ')} cards in ${PICKUP.finishes.map((f) => FINISHES[f].label).join(' or ')}. Never Large, Giant or Luxe.`,
);
line(`- The customer pays ${gbp(MODES.pickup.price.regular)}. No pick-up string says "free".`);
line(
  `- Cost to Dearly: partner payout ${gbp(PICKUP.partnerPayout)} + stock ${gbp(PICKUP.stock)} = ${gbp(PICKUP.partnerPayout + PICKUP.stock)}, which replaces the print cost. There is no delivery cost line and no guarantee reserve.`,
);
line(`- Shown to the customer as "${PICKUP_PROMISE}", never "arrives".`);
line(
  `- Moonpig comparison sentence: "${quote({ size: 'regular', finish: 'classic', mode: 'pickup' }).moonpigNote}"`,
);
line();

line('## 5. Delivery mode rule');
line();
line(
  'Giant always travels tracked. Seven or more days ahead: advance post. Two to six days: tracked. Under two days: pick-up when rule 4 allows it, otherwise tracked with an on-the-day eCard offer. When the default would be pick-up but the finish is Luxe, tracked is used.',
);
line();
const days = [0, 1, 2, 6, 7, 30];
table(
  ['Card', ...days.map((d) => `${d} days`)],
  [
    ['Regular Signature', ...days.map((d) => MODES[chooseMode('regular', d, 'signature')].label)],
    ['Regular Classic', ...days.map((d) => MODES[chooseMode('regular', d, 'classic')].label)],
    ['Regular Luxe', ...days.map((d) => MODES[chooseMode('regular', d, 'luxe')].label)],
    ['Large (any finish)', ...days.map((d) => MODES[chooseMode('large', d, 'classic')].label)],
    ['Giant (any finish)', ...days.map((d) => MODES[chooseMode('giant', d, 'signature')].label)],
  ],
);

line('## 6. Digital');
line();
line(`- Digital copy with a printed card: ${gbp(DIGITAL.paired)}.`);
line(`- Standalone eCard: ${gbp(DIGITAL.standalone)}.`);
line('- The QR recipient page is free.');
line();

line('## 7. Gifts');
line();
line(`Gift cost to Dearly = price / 1.2 × ${GIFT_COST_SHARE}.`);
line();
table(
  ['Gift', 'Price', 'Cost'],
  GIFTS.map((g) => [
    g.label,
    gbp(g.price),
    p(Math.round((toPence(g.price) / 1.2) * GIFT_COST_SHARE)),
  ]),
);

line('## 8. Per-order costs (editable on Operations)');
line();
table(
  ['Cost', 'Value'],
  [
    [
      'Payment',
      `${(DEFAULT_COSTS.payPct * 100).toFixed(1)}% of the total + ${gbp(DEFAULT_COSTS.payFixed)}`,
    ],
    ['AI', gbp(DEFAULT_COSTS.ai)],
    ['Service', gbp(DEFAULT_COSTS.service)],
    [
      'Guarantee reserve',
      `${gbp(DEFAULT_COSTS.guarantee)} only when the mode carries the guarantee`,
    ],
    ['Team', `£${DEFAULT_COSTS.teamPerYear.toLocaleString('en-GB')} a year`],
  ],
);

line('## 9. Moonpig comparison (printed Regular cards only)');
line();
const mpAdvance = quote({ size: 'regular', finish: 'signature', mode: 'advance' });
const mpTracked = quote({ size: 'regular', finish: 'signature', mode: 'tracked' });
table(
  ['Item', 'Value'],
  [
    ['Moonpig Regular card', gbp(MOONPIG.card)],
    ['Moonpig first class', gbp(MOONPIG.firstClass)],
    ['Moonpig tracked', gbp(MOONPIG.tracked)],
    ['Compared against advance post', p(mpAdvance.moonpigPence ?? 0)],
    ['Compared against tracked', p(mpTracked.moonpigPence ?? 0)],
  ],
);
line(
  'Saving = Moonpig total − (Dearly card + delivery). Large and Giant cards are never compared. When the saving would be negative the comparison line is hidden.',
);
line();

line('## 10. Guarantee');
line();
line(
  `Advance and tracked only. A missed date gives a full refund and a single-use code for ${Math.round(GUARANTEE.nextCardDiscountPct * 100)}% off the card price (not delivery) of the next order, a tracked reprint when two or more days remain, and an on-the-day eCard always.`,
);
line();

line('## 11. First card free');
line();
const fcf = quote({ size: 'regular', finish: 'signature', mode: 'advance', firstCardFree: true });
line(
  `Once per account, for ${FIRST_CARD_FREE.sizes.map((s) => SIZES[s].label).join(', ')} ${FIRST_CARD_FREE.finishes.map((f) => FINISHES[f].label).join(' or ')} only, when the account holds at least ${FIRST_CARD_FREE.minReminders} reminder dates and has not ordered a printed card before. The card price is 0; delivery, the digital copy and gifts are charged. Example: Regular Signature by advance post totals ${p(fcf.totalPence)} (${p(fcf.exVatPence)} ex VAT, contribution ${p(fcf.contributionPence)}).`,
);
line();

line('## 12. Business (excluding VAT, Regular Signature)');
line();
table(
  ['Option', 'Price per card', 'Contribution per card'],
  [
    [
      'Posted',
      gbp(BUSINESS.posted),
      p(businessUnitContributionPence(businessUnitPricePence(100, 'posted'), 'posted')),
    ],
    [
      'Posted, 250 or more a year',
      gbp(BUSINESS.tier250),
      p(businessUnitContributionPence(businessUnitPricePence(250, 'posted'), 'posted')),
    ],
    [
      'Posted, 2,000 or more a year',
      gbp(BUSINESS.tier2000),
      p(businessUnitContributionPence(businessUnitPricePence(2000, 'posted'), 'posted')),
    ],
    [
      'Office drop (flat)',
      gbp(BUSINESS.officeDrop),
      p(businessUnitContributionPence(businessUnitPricePence(5000, 'officeDrop'), 'officeDrop')),
    ],
  ],
);
const batch = priceBatch(600, {
  option: 'posted',
  finish: 'signature',
  annualCards: 600,
  automate: false,
});
const annual = annualCalculator({ cardsPerYear: 400, postedShare: 0.7, automate: true });
line(
  `- Finishes offered to business: ${BUSINESS.finishes.map((f) => FINISHES[f].label).join(', ')}. No Luxe.`,
);
line(
  `- Automate plan: ${gbp(BUSINESS.automateMonthly)} a month, optional; the first ${BUSINESS.freeCards} cards are free (once). Example: ${annual.includedCards} cards included, subscription ${p(annual.subscriptionPence)} a year.`,
);
line(
  `- Business payment cost: ${pct(BUSINESS.paymentPct)} of the invoice. Office drop delivery cost: ${gbp(BUSINESS_COSTS.officeDropDelivery)} a card. Posted delivery cost: ${gbp(MODES.advance.cost.regular)} a card.`,
);
line(`- Moonpig comparator: ${gbp(BUSINESS.moonpigPerCard)} a card.`);
line(
  `- Example batch: 600 posted cards at the 250 tier total ${p(batch.totalPence)} and contribute ${p(batch.contributionPence)} (${p(batch.contributionPerCardPence)} a card).`,
);
line();

line('## 13. Florist channel');
line();
line(`- Referral fee: ${gbp(FLORIST.referralFee)} per new account.`);
line(
  `- Commission: ${FLORIST.commissionPct}% of the flower basket. Sample basket ${gbp(FLORIST.sampleBasket)} gives ${p(expectedCommissionPence(toPence(FLORIST.sampleBasket)))}.`,
);
line();

line('## 14. Operations formulas');
line();
const e = economics(DEFAULT_COSTS);
table(
  ['Figure', 'Value'],
  [
    [
      'Blended contribution',
      `${pct(BLEND.classic)} Classic + ${pct(BLEND.signature)} Signature + ${pct(BLEND.luxe)} Luxe, Regular, advance post = ${p(e.blendedContributionPence)}`,
    ],
    [
      'Break-even orders a year',
      `team cost / blended contribution = ${e.breakEvenOrders.toLocaleString('en-GB')}`,
    ],
    ['Team cost per order at 210,000 orders', p(e.teamCostPerOrderPence(210_000))],
    [
      'Postage saved (estimate)',
      `advance orders × ${gbp(STAMPS.firstClass - STAMPS.secondClass)} (first class ${gbp(STAMPS.firstClass)} − second class ${gbp(STAMPS.secondClass)})`,
    ],
  ],
);

line('## 15. Expected values');
line();
const cases: { name: string; input: QuoteInput }[] = [
  {
    name: 'Regular Classic, advance',
    input: { size: 'regular', finish: 'classic', mode: 'advance' },
  },
  {
    name: 'Regular Signature, advance',
    input: { size: 'regular', finish: 'signature', mode: 'advance' },
  },
  { name: 'Regular Luxe, advance', input: { size: 'regular', finish: 'luxe', mode: 'advance' } },
  {
    name: 'Regular Signature, tracked',
    input: { size: 'regular', finish: 'signature', mode: 'tracked' },
  },
  {
    name: 'Regular Signature, pick-up',
    input: { size: 'regular', finish: 'signature', mode: 'pickup' },
  },
  {
    name: 'Regular Classic, pick-up',
    input: { size: 'regular', finish: 'classic', mode: 'pickup' },
  },
  {
    name: 'Regular Signature, advance, digital copy',
    input: { size: 'regular', finish: 'signature', mode: 'advance', digital: true },
  },
  {
    name: 'Regular Signature, advance, flowers',
    input: { size: 'regular', finish: 'signature', mode: 'advance', gift: 'flowers' },
  },
  { name: 'Standalone eCard', input: { size: 'regular', finish: 'signature', mode: 'ecard' } },
  {
    name: 'First card free, Regular Signature, advance',
    input: { size: 'regular', finish: 'signature', mode: 'advance', firstCardFree: true },
  },
];
table(
  ['Case', 'Total', 'Ex VAT', 'Contribution', 'Moonpig', 'Saving'],
  cases.map(({ name, input }) => {
    const q = quote(input);
    return [
      name,
      p(q.totalPence),
      p(q.exVatPence),
      p(q.contributionPence),
      q.moonpigPence == null ? (q.moonpigNote ?? 'none') : p(q.moonpigPence),
      q.savingPence == null
        ? 'none'
        : q.savingPence > 0
          ? p(q.savingPence)
          : `${p(q.savingPence)} (hidden)`,
    ];
  }),
);

line('## 16. Full matrix');
line();
const matrix: string[][] = [];
for (const s of sizes) {
  for (const f of finishes) {
    for (const m of allowedModes(s, f)) {
      const q = quote({ size: s, finish: f, mode: m });
      matrix.push([
        `${SIZES[s].label} ${FINISHES[f].label}`,
        MODES[m].label,
        p(q.totalPence),
        p(q.exVatPence),
        p(q.costs.totalPence),
        p(q.contributionPence),
        q.moonpigPence == null ? '—' : p(q.moonpigPence),
        q.savingPence == null ? '—' : p(q.savingPence),
      ]);
    }
  }
}
table(['Card', 'Mode', 'Total', 'Ex VAT', 'Cost', 'Contribution', 'Moonpig', 'Saving'], matrix);

line('## Not in the pilot');
line();
line(
  'Early-approval discount, credit packs, seasonal discounts, tiered office-drop pricing, Luxe for business, and any Moonpig Large or Giant price.',
);

async function main(): Promise<void> {
  const config = (await prettier.resolveConfig('docs/pricing.md')) ?? {};
  const text = await prettier.format(out.join('\n') + '\n', { ...config, parser: 'markdown' });
  writeFileSync('docs/pricing.md', text);
  console.log('docs/pricing.md written');
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
